require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectPhasesController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectPhase. As you add validations to ProjectPhase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  before(:each) do
    @admin = Factory(:admin)
    sign_in @admin
  end


  describe "GET index" do
    it "assigns all project_phases as @project_phases" do
      project_phase = ProjectPhase.create! valid_attributes
      get :index
      assigns(:project_phases).should eq([project_phase])
    end
  end

  describe "GET show" do
    it "assigns the requested project_phase as @project_phase" do
      project_phase = ProjectPhase.create! valid_attributes
      get :show, :id => project_phase.id.to_s
      assigns(:project_phase).should eq(project_phase)
    end
  end

  describe "GET new" do
    it "assigns a new project_phase as @project_phase" do
      get :new
      assigns(:project_phase).should be_a_new(ProjectPhase)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_phase as @project_phase" do
      project_phase = ProjectPhase.create! valid_attributes
      get :edit, :id => project_phase.id.to_s
      assigns(:project_phase).should eq(project_phase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectPhase" do
        expect {
          post :create, :project_phase => valid_attributes
        }.to change(ProjectPhase, :count).by(1)
      end

      it "assigns a newly created project_phase as @project_phase" do
        post :create, :project_phase => valid_attributes
        assigns(:project_phase).should be_a(ProjectPhase)
        assigns(:project_phase).should be_persisted
      end

      it "redirects to the created project_phase" do
        post :create, :project_phase => valid_attributes
        response.should redirect_to(ProjectPhase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_phase as @project_phase" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectPhase.any_instance.stub(:save).and_return(false)
        post :create, :project_phase => {}
        assigns(:project_phase).should be_a_new(ProjectPhase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectPhase.any_instance.stub(:save).and_return(false)
        post :create, :project_phase => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_phase" do
        project_phase = ProjectPhase.create! valid_attributes
        # Assuming there are no other project_phases in the database, this
        # specifies that the ProjectPhase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectPhase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => project_phase.id, :project_phase => {'these' => 'params'}
      end

      it "assigns the requested project_phase as @project_phase" do
        project_phase = ProjectPhase.create! valid_attributes
        put :update, :id => project_phase.id, :project_phase => valid_attributes
        assigns(:project_phase).should eq(project_phase)
      end

      it "redirects to the project_phase" do
        project_phase = ProjectPhase.create! valid_attributes
        put :update, :id => project_phase.id, :project_phase => valid_attributes
        response.should redirect_to(project_phase)
      end
    end

    describe "with invalid params" do
      it "assigns the project_phase as @project_phase" do
        project_phase = ProjectPhase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectPhase.any_instance.stub(:save).and_return(false)
        put :update, :id => project_phase.id.to_s, :project_phase => {}
        assigns(:project_phase).should eq(project_phase)
      end

      it "re-renders the 'edit' template" do
        project_phase = ProjectPhase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectPhase.any_instance.stub(:save).and_return(false)
        put :update, :id => project_phase.id.to_s, :project_phase => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_phase" do
      project_phase = ProjectPhase.create! valid_attributes
      expect {
        delete :destroy, :id => project_phase.id.to_s
      }.to change(ProjectPhase, :count).by(-1)
    end

    it "redirects to the project_phases list" do
      project_phase = ProjectPhase.create! valid_attributes
      delete :destroy, :id => project_phase.id.to_s
      response.should redirect_to(project_phases_url)
    end
  end

end
